### **1. Print "+"**

**Description:**
Given a single positive odd integer 'n' greater than 2, create a NumPy array of size (n x n) with all zeros and ones such that the ones make a shape like '+'. The lines of the plus must be present at the middle row and column.
Hint: Start by creating a (n x n) array with all zeroes using the np.zeros() function and then fill in the ones at the appropriate indices. Use integer division (//) to access the middle rows and columns

**Examples:**
Input 1:
3
Output 1:

```
[[0 1 0]
 [1 1 1]
 [0 1 0]]
```

Input 2:
5
Output 1:

```
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
```

**Explanation:** Notice that the 1s in the arrays make a shape like '+'.


In [26]:
import numpy as np 

# Create an (nxn) array with all zeros
z = np.zeros((5,5), dtype='int')

n=5

z[n//2,:] = 1
z[:,n//2] = 1
print(z)


[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


### **2. Weight Loss**

**Description:** With your 25th birthday fast approaching, you decide to get in shape and lose some weight. You record your weight every day for five weeks starting on a Monday.

```
import numpy as np

weights = 175 - np.arange(5*7)/5
print(weights)
```

Given these daily weights, build an array with your average weight per weekend



In [19]:
import numpy as np

weights = 175 - np.arange(5*7)/5

# Reshape the weights array into a 5x7 matrix
weights_matrix = weights.reshape(5, 7)

weekend_weights = weights_matrix[:, 5:]
average_weight = np.mean(weekend_weights, axis=1)

print(average_weight)


[173.9 172.5 171.1 169.7 168.3]


### **3. Gaming Nicks**

**Description:** You want to start playing a first person shooter game and you are confused to find a gaming nick for yourself, hence you asked your friends and you’ve compiled the names into a Series called nicks.
import numpy as np
import pandas as pd



```
nicks = pd.Series([
    'Pik', 'Devine99', 'Spawn', 'Prodigy', 'Superkiller420', 'Pik', 'tornado',
    'tornado', 'roger', 'Gabriel', 'Chad', 'Ryan', 'Phoenix', 'Phoenix', 'Phoenix',
    'Phoenix', 'Zeltron', 'Ryan', 'Ruger', 'Ruger', 'roger',
    'roger', 'Chad', 'Chad', 'Gabriel'], dtype='string')
```

Determine how many people voted for the names ‘Phoenix’, ‘roger’, and ‘Pik’.


In [35]:
import numpy as np
import pandas as pd

nicks = pd.Series([
    'Pik', 'Devine99', 'Spawn', 'Prodigy', 'Superkiller420', 'Pik', 'tornado',
    'tornado', 'roger', 'Gabriel', 'Chad', 'Ryan', 'Phoenix', 'Phoenix', 'Phoenix',
    'Phoenix', 'Zeltron', 'Ryan', 'Ruger', 'Ruger', 'roger',
    'roger', 'Chad', 'Chad', 'Gabriel'], dtype='string')

vote_Phoenix=nicks.loc[nicks=="Phoenix"].count()
vote_roger=nicks.loc[nicks=="roger"].count()
vote_Pik=nicks.loc[nicks=="Pik"].count()


print("Phoenix:", vote_Phoenix)
print("roger:", vote_roger)
print("Pik:", vote_Pik)

Phoenix: 4
roger: 3
Pik: 2
